// AUTO-GENERATED by `arkveil generate typescript`. Do not edit by hand.
//
// This file types the Arkveil SDK for TypeScript by declaration-merging into
// the `arkveil` package. Import it once (a side-effect import is enough) and
// permission codes plus `user` / `context` attributes become typed across
// `checkPermission`, the Node `permissionPoint` middleware, and the NestJS
// `@PermissionPoint` decorator. Regenerate whenever codes or schemas change.

/** Union of every permission code defined in this Arkveil project. */
export type ArkveilCodes =
  | "content-service.article-delete"
  | "user-service.user-create"
  | "UserService.banUser";

/** Shape of `user` attributes (from `arkveil schemas get user`). */
export interface ArkveilUserAttributes {
  /** Stable user id. */
  id?: string;
  role: "admin" | "editor" | "viewer";
  teams?: string[];
}

/** Shape of `context` attributes (from `arkveil schemas get context`). */
export interface ArkveilContextAttributes {
  ipAddress?: string;
  region?: "EU" | "US";
}

// Register the generated types globally so the default `Arkveil` generics
// pick them up automatically — no need to pass them everywhere.
declare module "arkveil" {
  interface ArkveilCodeRegistry {
    codes: ArkveilCodes;
  }
  interface ArkveilUserRegistry {
    attributes: ArkveilUserAttributes;
  }
  interface ArkveilContextRegistry {
    attributes: ArkveilContextAttributes;
  }
}
