import type { Logger } from "./types/logger";
import { fetchWithRetry } from "./utils/fetch-with-retry";
import {
  METADATA_MISSING,
  MODE_UNAVAILABLE,
  normalizeDatasetCode,
  type ReadConditionRequest,
  type ReadConditionResponse,
  type WriteChecksRequest,
  type WriteChecksResponse,
} from "./data-conditions";

/**
 * Registry interface for permission codes.
 *
 * Augment this via declaration merging — typically from a file generated by
 * the Arkveil CLI — to get autocomplete and type-checking for permission codes
 * everywhere the SDK accepts a `code`: the {@link Arkveil} methods, the Node
 * `permissionPoint` middleware, and the NestJS `@PermissionPoint` decorator.
 *
 * @example
 * ```ts
 * // arkveil.generated.ts (auto-generated by `arkveil generate typescript`)
 * declare module "arkveil" {
 *   interface ArkveilCodeRegistry {
 *     codes: "content-service.article-delete" | "user-service.user-create";
 *   }
 * }
 * ```
 */
export interface ArkveilCodeRegistry {}

/**
 * The union of registered permission codes, resolved from
 * {@link ArkveilCodeRegistry}. Falls back to `string` when the registry has
 * not been augmented, so untyped usage keeps working.
 */
export type ArkveilCode = ArkveilCodeRegistry extends { codes: infer C }
  ? C extends string
    ? C
    : string
  : string;

/**
 * Registry interface for **user** attributes.
 *
 * Augment this via declaration merging — typically from the file written by
 * `arkveil generate typescript` out of your project's user attribute JSON
 * Schema — to type the `user` object everywhere the SDK touches it: the
 * `getUserAttributes` extractor, {@link PermissionCheckRequest}, and
 * {@link Arkveil.checkPermission}.
 *
 * @example
 * ```ts
 * // arkveil.generated.ts (auto-generated by `arkveil generate typescript`)
 * declare module "arkveil" {
 *   interface ArkveilUserRegistry {
 *     attributes: { id: string; role: "admin" | "editor" | "viewer" };
 *   }
 * }
 * ```
 */
export interface ArkveilUserRegistry {}

/**
 * Registry interface for **context** attributes. The context-side twin of
 * {@link ArkveilUserRegistry}; augmented by the same `arkveil generate typescript`
 * file.
 *
 * @example
 * ```ts
 * declare module "arkveil" {
 *   interface ArkveilContextRegistry {
 *     attributes: { ipAddress?: string; region?: "EU" | "US" };
 *   }
 * }
 * ```
 */
export interface ArkveilContextRegistry {}

/**
 * The shape of user attributes, resolved from {@link ArkveilUserRegistry}.
 * Falls back to `Record<string, any>` when the registry has not been
 * augmented, so untyped usage keeps working.
 */
export type ArkveilUser = ArkveilUserRegistry extends { attributes: infer U }
  ? U extends Record<string, any>
    ? U
    : Record<string, any>
  : Record<string, any>;

/**
 * The shape of context attributes, resolved from {@link ArkveilContextRegistry}.
 * Falls back to `Record<string, any>` when the registry has not been augmented.
 */
export type ArkveilContext = ArkveilContextRegistry extends {
  attributes: infer C;
}
  ? C extends Record<string, any>
    ? C
    : Record<string, any>
  : Record<string, any>;

export interface ArkveilParams<
  TUser extends Record<string, any> = ArkveilUser,
  TContext extends Record<string, any> = ArkveilContext,
> {
  serviceUrl: string;
  apiKey: string;
  version?: "v1";
  timeout?: number;
  retryAttempts?: number;
  logger?: Logger;

  getUserAttributes?: (req: any) => TUser | Promise<TUser>;
  getContextAttributes?: (req: any) => TContext | Promise<TContext>;
  onDenied?: (req: any, res: any, reason?: string) => void | Promise<void>;
}

export interface PermissionCheckRequest<
  TCode extends string = ArkveilCode,
  TUser extends Record<string, any> = ArkveilUser,
  TContext extends Record<string, any> = ArkveilContext,
> {
  actionCode: TCode;
  user: TUser;
  context: TContext;
}

export interface PermissionCheckResponse {
  granted: boolean;
}

export class Arkveil<
  TCode extends string = ArkveilCode,
  TUser extends Record<string, any> = ArkveilUser,
  TContext extends Record<string, any> = ArkveilContext,
> {
  private serviceUrl: string;
  private apiKey: string;
  private version: ArkveilParams["version"] = "v1";
  private timeout?: number;
  private retryAttempts?: number;

  protected getUserAttributes?: (req: any) => TUser | Promise<TUser>;
  protected getContextAttributes?: (req: any) => TContext | Promise<TContext>;
  protected onDenied?: (req: any, res: any) => void | Promise<void>;

  protected logger?: Logger;

  constructor(params: ArkveilParams<TUser, TContext>) {
    this.serviceUrl = params.serviceUrl.replace(/\/$/, "");
    this.apiKey = params.apiKey;
    this.version = params.version || "v1";
    this.timeout = params.timeout;
    this.retryAttempts = params.retryAttempts;

    this.getUserAttributes = params.getUserAttributes;
    this.getContextAttributes = params.getContextAttributes;
    this.onDenied = params.onDenied;
    this.logger = params.logger;
  }

  /**
   * Build a permission check request for the given code, resolving user and
   * context attributes from the configured `getUserAttributes` /
   * `getContextAttributes` extractors. Shared by all platform SDKs so that
   * attribute resolution behaves identically everywhere.
   *
   * @param code - The permission code to check
   * @param req - The platform request object passed to the extractors
   */
  public async buildPermissionRequest(
    code: TCode,
    req: any,
  ): Promise<PermissionCheckRequest<TCode, TUser, TContext>> {
    const request: PermissionCheckRequest<TCode, TUser, TContext> = {
      actionCode: code,
      user: {} as TUser,
      context: {} as TContext,
    };

    if (this.getUserAttributes) {
      request.user = {
        ...request.user,
        ...(await this.getUserAttributes(req)),
      } as TUser;
    }

    if (this.getContextAttributes) {
      request.context = {
        ...request.context,
        ...(await this.getContextAttributes(req)),
      } as TContext;
    }

    return request;
  }

  /**
   * Check if a user has permission to perform an action
   */
  public async checkPermission(
    request: PermissionCheckRequest<TCode, TUser, TContext>,
  ): Promise<PermissionCheckResponse> {
    const url = `${this.serviceUrl}/api/${this.version}/abac/permissions/check`;

    try {
      const response = await fetchWithRetry(
        url,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": `${this.apiKey}`,
          },
          body: JSON.stringify(request),
        },
        {
          timeout: this.timeout,
          retryAttempts: this.retryAttempts,
        },
      );

      if (!response.ok) {
        throw new Error(
          `Permission check failed: ${response.status} ${response.statusText}`,
        );
      }

      const data = (await response.json()) as PermissionCheckResponse;

      return data;
    } catch (error) {
      this.logger?.error("Permission check failed:", error);
      return {
        granted: false,
      };
    }
  }

  /**
   * Fetch the SQL read condition for a dataset: one boolean expression to AND
   * into the query's WHERE clause (`POST /abac/conditions/read`).
   *
   * `readCondition: "FALSE"` is a normal response ("no applicable policy ⇒ no
   * rows") — apply it like any other condition; never fall back to unfiltered
   * access. Pass `alias` whenever the protected table is aliased or joined.
   *
   * Fail-closed: transport failures and non-OK responses are logged and
   * return `{ readCondition: "FALSE", mode: "UNAVAILABLE" }`, so a degraded
   * Arkveil never widens access. A malformed `datasetCode` throws instead —
   * that is a programming/configuration error, not a runtime condition.
   */
  public async buildReadCondition(
    request: ReadConditionRequest<TUser, TContext>,
  ): Promise<ReadConditionResponse> {
    const datasetCode = normalizeDatasetCode(request.datasetCode);

    try {
      const data = await this.postConditions<ReadConditionResponse>("read", {
        datasetCode,
        user: request.user,
        context: request.context,
        ...(request.alias !== undefined ? { alias: request.alias } : {}),
      });
      this.flagDegradedMode("read condition", datasetCode, data.mode);
      return data;
    } catch (error) {
      this.logger?.error(
        `[Arkveil] Read condition request failed for dataset ${datasetCode}; failing closed (FALSE):`,
        error,
      );
      return { readCondition: "FALSE", mode: MODE_UNAVAILABLE };
    }
  }

  /**
   * Fetch the SQL write check for a mutation (`POST /abac/conditions/write`):
   * a single statement returning one boolean — `true` ⇒ the mutation touches
   * no forbidden row. Execute it against the application's database inside
   * the mutation's transaction and roll back on `false`.
   *
   * When it runs relative to the mutation statement is part of the contract:
   * - CREATE: **after** the insert (the new rows must exist to be evaluated),
   *   with the just-inserted ids.
   * - UPDATE: **before and after** the update, with the targeted ids.
   * - DELETE: **before** the delete, with the targeted ids.
   *
   * `ids` are sent as strings; the server casts them to the dataset's
   * primary-key type. With `ids` omitted, `writeSql` contains the `{{ids}}`
   * placeholder to fill via `substituteIds`. A `reason` of
   * `"METADATA_MISSING"` means the dataset isn't registered in Arkveil — a
   * configuration gap, not a policy deny.
   *
   * Fail-closed: transport failures and non-OK responses are logged and
   * return `{ writeSql: "SELECT FALSE", invariantSql: [], mode: "UNAVAILABLE" }`.
   * A malformed `datasetCode` throws instead — that is a
   * programming/configuration error, not a runtime condition.
   */
  public async buildWriteChecks(
    request: WriteChecksRequest<TUser, TContext>,
  ): Promise<WriteChecksResponse> {
    const datasetCode = normalizeDatasetCode(request.datasetCode);

    try {
      const data = await this.postConditions<WriteChecksResponse>("write", {
        datasetCode,
        user: request.user,
        context: request.context,
        ...(request.ids !== undefined
          ? { ids: request.ids.map((id) => String(id)) }
          : {}),
      });
      if (data.reason === METADATA_MISSING) {
        this.logger?.error(
          `[Arkveil] Write check for dataset ${datasetCode} denied with reason METADATA_MISSING: ` +
            "the dataset is not registered in Arkveil (configuration gap, not a policy deny).",
        );
      }
      this.flagDegradedMode("write checks", datasetCode, data.mode);
      return data;
    } catch (error) {
      this.logger?.error(
        `[Arkveil] Write checks request failed for dataset ${datasetCode}; failing closed (SELECT FALSE):`,
        error,
      );
      return {
        writeSql: "SELECT FALSE",
        invariantSql: [],
        mode: MODE_UNAVAILABLE,
      };
    }
  }

  /**
   * POST to a data-conditions endpoint. Shares base URL, versioning, auth,
   * and retry behavior with `checkPermission`; throws on non-OK responses so
   * the callers can apply their fail-closed defaults.
   */
  private async postConditions<T>(
    endpoint: "read" | "write",
    body: Record<string, unknown>,
  ): Promise<T> {
    const url = `${this.serviceUrl}/api/${this.version}/abac/conditions/${endpoint}`;

    const response = await fetchWithRetry(
      url,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": `${this.apiKey}`,
        },
        body: JSON.stringify(body),
      },
      {
        timeout: this.timeout,
        retryAttempts: this.retryAttempts,
      },
    );

    if (!response.ok) {
      const message = await response.text().catch(() => "");
      throw new Error(
        `Conditions request failed: ${response.status} ${response.statusText}${
          message ? ` — ${message}` : ""
        }`,
      );
    }

    // Responses gain fields additively; anything unknown is passed through.
    return (await response.json()) as T;
  }

  /** Non-"NORMAL" modes mean the serving side is degraded (e.g. a sidecar
   * past its staleness bound): the SQL is still honored, but the call is
   * flagged in diagnostics. */
  private flagDegradedMode(
    operation: string,
    datasetCode: string,
    mode: string,
  ): void {
    if (mode !== "NORMAL") {
      this.logger?.warn(
        `[Arkveil] ${operation} for dataset ${datasetCode} served in degraded mode "${mode}".`,
      );
    }
  }

  /**
   * Handle denied access - runtime agnostic base implementation
   * Platform-specific SDKs should override this method
   *
   * @param req - Request object
   * @param res - Response object
   * @param next - Next function (optional)
   * @param onDenied - Custom denial handler (optional)
   */
  protected handleDenied(
    req: any,
    res: any,
    next: any,
    onDenied?: (req: any, res: any) => void | Promise<void>,
  ) {
    const customHandler = onDenied || this.onDenied;

    if (customHandler) {
      return customHandler(req, res);
    }

    // Platform-specific implementations (Node.js, etc.) should override this method
    throw new Error(
      "Access denied. No custom onDenied handler provided. " +
        "Either provide an onDenied handler in the constructor or use a platform-specific SDK.",
    );
  }
}
