import type { Logger } from "./types/logger";
import { fetchWithRetry } from "./utils/fetch-with-retry";
import {
  applyWriteChecksContract,
  assertTouchOperation,
  CONTRACT_VIOLATION,
  DENY_CONDITION,
  DENY_SQL,
  denyWriteChecks,
  METADATA_MISSING,
  ATTRIBUTE_INCOMPATIBLE,
  MODE_NO_OP,
  MODE_UNAVAILABLE,
  normalizeDatasetCode,
  prepareWriteChecksIds,
  type ReadConditionRequest,
  type ReadConditionResponse,
  type TouchConditionRequest,
  type TouchConditionResponse,
  type WriteChecksRequest,
  type WriteChecksResponse,
} from "./data-conditions";

/**
 * Registry interface for permission codes.
 *
 * Augment this via declaration merging — typically from a file generated by
 * the Arkveil CLI — to get autocomplete and type-checking for permission codes
 * everywhere the SDK accepts a `code`: the {@link Arkveil} methods, the Node
 * `permissionPoint` middleware, and the NestJS `@PermissionPoint` decorator.
 *
 * @example
 * ```ts
 * // arkveil.generated.ts (auto-generated by `arkveil generate typescript`)
 * declare module "arkveil" {
 *   interface ArkveilCodeRegistry {
 *     codes: "content-service.article-delete" | "user-service.user-create";
 *   }
 * }
 * ```
 */
export interface ArkveilCodeRegistry {}

/**
 * The union of registered permission codes, resolved from
 * {@link ArkveilCodeRegistry}. Falls back to `string` when the registry has
 * not been augmented, so untyped usage keeps working.
 */
export type ArkveilCode = ArkveilCodeRegistry extends { codes: infer C }
  ? C extends string
    ? C
    : string
  : string;

/**
 * Registry interface for **user** attributes.
 *
 * Augment this via declaration merging — typically from the file written by
 * `arkveil generate typescript` out of your project's user attribute JSON
 * Schema — to type the `user` object everywhere the SDK touches it: the
 * `getUserAttributes` extractor, {@link PermissionCheckRequest}, and
 * {@link Arkveil.checkPermission}.
 *
 * @example
 * ```ts
 * // arkveil.generated.ts (auto-generated by `arkveil generate typescript`)
 * declare module "arkveil" {
 *   interface ArkveilUserRegistry {
 *     attributes: { id: string; role: "admin" | "editor" | "viewer" };
 *   }
 * }
 * ```
 */
export interface ArkveilUserRegistry {}

/**
 * Registry interface for **context** attributes. The context-side twin of
 * {@link ArkveilUserRegistry}; augmented by the same `arkveil generate typescript`
 * file.
 *
 * @example
 * ```ts
 * declare module "arkveil" {
 *   interface ArkveilContextRegistry {
 *     attributes: { ipAddress?: string; region?: "EU" | "US" };
 *   }
 * }
 * ```
 */
export interface ArkveilContextRegistry {}

/**
 * The shape of user attributes, resolved from {@link ArkveilUserRegistry}.
 * Falls back to `Record<string, any>` when the registry has not been
 * augmented, so untyped usage keeps working.
 */
export type ArkveilUser = ArkveilUserRegistry extends { attributes: infer U }
  ? U extends Record<string, any>
    ? U
    : Record<string, any>
  : Record<string, any>;

/**
 * The shape of context attributes, resolved from {@link ArkveilContextRegistry}.
 * Falls back to `Record<string, any>` when the registry has not been augmented.
 */
export type ArkveilContext = ArkveilContextRegistry extends {
  attributes: infer C;
}
  ? C extends Record<string, any>
    ? C
    : Record<string, any>
  : Record<string, any>;

export interface ArkveilParams<
  TUser extends Record<string, any> = ArkveilUser,
  TContext extends Record<string, any> = ArkveilContext,
> {
  serviceUrl: string;
  apiKey: string;
  version?: "v1";
  timeout?: number;
  retryAttempts?: number;
  logger?: Logger;

  getUserAttributes?: (req: any) => TUser | Promise<TUser>;
  getContextAttributes?: (req: any) => TContext | Promise<TContext>;
  onDenied?: (req: any, res: any, reason?: string) => void | Promise<void>;
}

export interface PermissionCheckRequest<
  TCode extends string = ArkveilCode,
  TUser extends Record<string, any> = ArkveilUser,
  TContext extends Record<string, any> = ArkveilContext,
> {
  actionCode: TCode;
  user: TUser;
  context: TContext;
}

/**
 * The `reason` a permission check carries when Arkveil Cloud alone cannot
 * decide a rule: it reads a dataset (`exists <dataset> where …`), which only a
 * connected `arkveil-runtime` sidecar can evaluate. The answer is
 * `granted: false` — fail-safe, not a policy deny. Point `serviceUrl` at a
 * sidecar for the real decision.
 */
export const RUNTIME_REQUIRED = "RUNTIME_REQUIRED";

/**
 * The `reason` a sidecar reports when a rule references a datasource it has
 * no connection for (`arkveil.runtime.datasources.<name>.*` missing, or the
 * mirror has not replicated the datasource yet). Denied fail-safe.
 */
export const DATASOURCE_UNRESOLVED = "DATASOURCE_UNRESOLVED";

/**
 * The `reason` a sidecar reports when the datasource query behind a rule
 * failed (connection or SQL error). Denied fail-safe.
 */
export const DATASOURCE_ERROR = "DATASOURCE_ERROR";

/**
 * The `reason` reported when the engine itself failed to evaluate a rule.
 * Denied fail-safe — a defect to investigate, not a rule at work.
 */
export const EVALUATION_ERROR = "EVALUATION_ERROR";

export interface PermissionCheckResponse {
  granted: boolean;
  /**
   * Why a denial is not an ordinary policy deny, when it is not: one of
   * {@link RUNTIME_REQUIRED}, {@link DATASOURCE_UNRESOLVED},
   * {@link DATASOURCE_ERROR}, {@link EVALUATION_ERROR} or
   * `ATTRIBUTE_INCOMPATIBLE` (a payload value of the wrong type for its
   * attribute schema, evaluated as absent). A grant carries no reason. Absent
   * on a plain policy deny.
   */
  reason?: string;
  /**
   * `"NORMAL"` unless the serving side is degraded — a sidecar past its
   * staleness bound answers `"MIRROR_STALE"`, and the SDK itself answers
   * `"UNAVAILABLE"` when the request failed. Honor the decision, watch the
   * diagnostics.
   */
  mode: string;
}

export class Arkveil<
  TCode extends string = ArkveilCode,
  TUser extends Record<string, any> = ArkveilUser,
  TContext extends Record<string, any> = ArkveilContext,
> {
  private serviceUrl: string;
  private apiKey: string;
  private version: ArkveilParams["version"] = "v1";
  private timeout?: number;
  private retryAttempts?: number;

  protected getUserAttributes?: (req: any) => TUser | Promise<TUser>;
  protected getContextAttributes?: (req: any) => TContext | Promise<TContext>;
  protected onDenied?: (
    req: any,
    res: any,
    reason?: string,
  ) => void | Promise<void>;

  protected logger?: Logger;

  constructor(params: ArkveilParams<TUser, TContext>) {
    this.serviceUrl = params.serviceUrl.replace(/\/$/, "");
    this.apiKey = params.apiKey;
    this.version = params.version || "v1";
    this.timeout = params.timeout;
    this.retryAttempts = params.retryAttempts;

    this.getUserAttributes = params.getUserAttributes;
    this.getContextAttributes = params.getContextAttributes;
    this.onDenied = params.onDenied;
    this.logger = params.logger;
  }

  /**
   * Build a permission check request for the given code, resolving user and
   * context attributes from the configured `getUserAttributes` /
   * `getContextAttributes` extractors. Shared by all platform SDKs so that
   * attribute resolution behaves identically everywhere.
   *
   * @param code - The permission code to check
   * @param req - The platform request object passed to the extractors
   */
  public async buildPermissionRequest(
    code: TCode,
    req: any,
  ): Promise<PermissionCheckRequest<TCode, TUser, TContext>> {
    const request: PermissionCheckRequest<TCode, TUser, TContext> = {
      actionCode: code,
      user: {} as TUser,
      context: {} as TContext,
    };

    if (this.getUserAttributes) {
      request.user = {
        ...request.user,
        ...(await this.getUserAttributes(req)),
      } as TUser;
    }

    if (this.getContextAttributes) {
      request.context = {
        ...request.context,
        ...(await this.getContextAttributes(req)),
      } as TContext;
    }

    return request;
  }

  /**
   * Check if a user has permission to perform an action.
   *
   * The answer carries the server's `reason` when a denial is not an
   * ordinary policy deny (see {@link PermissionCheckResponse.reason}) and
   * the `mode` it was served in. Fail-closed: transport failures and non-OK
   * responses are logged and return `{ granted: false, mode: "UNAVAILABLE" }`.
   */
  public async checkPermission(
    request: PermissionCheckRequest<TCode, TUser, TContext>,
  ): Promise<PermissionCheckResponse> {
    const url = `${this.serviceUrl}/api/${this.version}/abac/permissions/check`;

    try {
      const response = await fetchWithRetry(
        url,
        {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "x-api-key": `${this.apiKey}`,
          },
          body: JSON.stringify(request),
        },
        {
          timeout: this.timeout,
          retryAttempts: this.retryAttempts,
        },
      );

      if (!response.ok) {
        throw new Error(
          `Permission check failed: ${response.status} ${response.statusText}`,
        );
      }

      const data = (await response.json()) as PermissionCheckResponse;
      this.flagDegradedMode(
        "Permission check",
        `action ${request.actionCode}`,
        data.mode,
      );

      return data;
    } catch (error) {
      this.logger?.error("Permission check failed:", error);
      return {
        granted: false,
        mode: MODE_UNAVAILABLE,
      };
    }
  }

  /**
   * Fetch the SQL read condition for a dataset: one boolean expression to AND
   * into the query's WHERE clause (`POST /abac/conditions/read`).
   *
   * `readCondition: "FALSE"` is a normal response ("no applicable policy ⇒ no
   * rows") — apply it like any other condition; never fall back to unfiltered
   * access. Pass `alias` whenever the protected table is aliased or joined.
   *
   * Fail-closed: transport failures and non-OK responses are logged and
   * return `{ readCondition: "FALSE", mode: "UNAVAILABLE" }`, so a degraded
   * Arkveil never widens access. A malformed `datasetCode` throws instead —
   * that is a programming/configuration error, not a runtime condition.
   */
  public async buildReadCondition(
    request: ReadConditionRequest<TUser, TContext>,
  ): Promise<ReadConditionResponse> {
    const datasetCode = normalizeDatasetCode(request.datasetCode);

    try {
      const data = await this.postConditions<ReadConditionResponse>("read", {
        datasetCode,
        user: request.user,
        context: request.context,
        ...(request.alias !== undefined ? { alias: request.alias } : {}),
      });
      if (typeof data.readCondition !== "string") {
        this.logger?.error(
          `[Arkveil] Read condition for dataset ${datasetCode} violates the contract: ` +
            "the response is missing readCondition. Denying rather than proceeding unchecked.",
        );
        return {
          readCondition: DENY_CONDITION,
          mode: data.mode ?? MODE_UNAVAILABLE,
          reason: CONTRACT_VIOLATION,
        };
      }
      this.reportConfigurationGap("Read condition", datasetCode, data.reason);
      this.flagDegradedMode(
        "read condition",
        `dataset ${datasetCode}`,
        data.mode,
      );
      return data;
    } catch (error) {
      this.logger?.error(
        `[Arkveil] Read condition request failed for dataset ${datasetCode}; failing closed (${DENY_CONDITION}):`,
        error,
      );
      return { readCondition: DENY_CONDITION, mode: MODE_UNAVAILABLE };
    }
  }

  /**
   * Fetch the SQL checks for a mutation over **named rows**
   * (`POST /abac/conditions/write`). Each check is a single statement
   * returning one boolean; run it against the application's database inside
   * the mutation's transaction and roll back the whole mutation on `false`.
   * There is no partial success and no silent narrowing on named rows.
   *
   * Which check exists, and when it runs, is the contract:
   *
   * | Mutation | `touchSql`                        | `resultSql`                                 |
   * | -------- | --------------------------------- | ------------------------------------------- |
   * | CREATE   | absent                            | **after** the insert, over the inserted ids |
   * | UPDATE   | **before** the update, over `ids` | **after** the update, over the same ids     |
   * | DELETE   | **before** the delete, over `ids` | absent                                      |
   *
   * `ids` are required and non-empty for `UPDATE`/`DELETE` (sent as strings;
   * the server inlines them as typed literals) and must be absent for
   * `CREATE` — its `resultSql` comes back with the `{{ids}}` template, which
   * `resolveCreateResultSql` fills with the ids the insert produced. An empty
   * `ids` list targets nothing, so the SDK skips the request entirely and
   * returns `{ mode: "NO_OP" }` — run no checks and no mutation.
   *
   * A response missing a field its operation requires is a contract
   * violation: the SDK denies rather than proceeding unchecked, and reports
   * `reason: "CONTRACT_VIOLATION"`. A `reason` of `"METADATA_MISSING"` means
   * the dataset isn't registered in Arkveil. Both are configuration gaps,
   * logged distinctly from a policy deny.
   *
   * Fail-closed: transport failures and non-OK responses are logged and
   * return `SELECT FALSE` in every field the operation has, with
   * `mode: "UNAVAILABLE"`. A malformed `datasetCode`, an unknown
   * `operation`, or `ids` that contradict the operation throw instead — those
   * are programming/configuration errors, not runtime conditions.
   */
  public async buildWriteChecks(
    request: WriteChecksRequest<TUser, TContext>,
  ): Promise<WriteChecksResponse> {
    const datasetCode = normalizeDatasetCode(request.datasetCode);
    const operation = request.operation;
    const ids = prepareWriteChecksIds(operation, request.ids);

    // Nothing targeted ⇒ nothing to authorize: no request, no checks.
    if (ids !== undefined && ids.length === 0) {
      this.logger?.info(
        `[Arkveil] ${operation} on dataset ${datasetCode} targets no rows; skipping the write checks.`,
      );
      return { mode: MODE_NO_OP };
    }

    try {
      const data = await this.postConditions<WriteChecksResponse>("write", {
        datasetCode,
        user: request.user,
        context: request.context,
        operation,
        ...(ids !== undefined ? { ids } : {}),
      });

      const { response, violation } = applyWriteChecksContract(operation, data);
      if (violation) {
        this.logger?.error(
          `[Arkveil] Write checks for dataset ${datasetCode} violate the contract: ${violation}. ` +
            "Denying rather than proceeding unchecked.",
        );
      }
      this.reportConfigurationGap("Write checks", datasetCode, response.reason);
      this.flagDegradedMode(
        "write checks",
        `dataset ${datasetCode}`,
        response.mode,
      );
      return response;
    } catch (error) {
      this.logger?.error(
        `[Arkveil] Write checks request failed for dataset ${datasetCode}; failing closed (${DENY_SQL}):`,
        error,
      );
      return denyWriteChecks(operation, MODE_UNAVAILABLE);
    }
  }

  /**
   * Fetch the SQL touch condition for a **bulk** mutation whose rows are
   * named by a predicate rather than by id (`POST /abac/conditions/touch`):
   * a bare boolean expression over the operation's TOUCH union, aliased like
   * a read condition. AND it into the statement's WHERE clause — rows outside
   * the subject's touch union are simply not touched.
   *
   * The two recipes, each in one transaction:
   * - `DELETE … WHERE <predicate> AND (<touchCondition>)` — complete; a
   *   delete has no result phase.
   * - `UPDATE … WHERE <predicate> AND (<touchCondition>) RETURNING <pk>`,
   *   then `buildWriteChecks({ operation: "UPDATE", ids: <returned ids> })`
   *   and execute **only** `resultSql`. Never run `touchSql` post-hoc: the
   *   pre-state it checks no longer exists, so it would deny legitimate
   *   updates. Deny ⇒ roll back.
   *
   * `touchCondition: "FALSE"` is a normal response (an empty touch union ⇒
   * the statement affects zero rows), not an error. When the ids are known
   * upfront, prefer `buildWriteChecks` — deny-whole over the enumerated rows
   * is the stricter promise.
   *
   * Fail-closed: transport failures and non-OK responses are logged and
   * return `{ touchCondition: "FALSE", mode: "UNAVAILABLE" }`. A malformed
   * `datasetCode` or an operation with no WHERE clause (`CREATE`) throws.
   */
  public async buildTouchCondition(
    request: TouchConditionRequest<TUser, TContext>,
  ): Promise<TouchConditionResponse> {
    const datasetCode = normalizeDatasetCode(request.datasetCode);
    const operation = assertTouchOperation(request.operation);

    try {
      const data = await this.postConditions<TouchConditionResponse>("touch", {
        datasetCode,
        user: request.user,
        context: request.context,
        operation,
        ...(request.alias !== undefined ? { alias: request.alias } : {}),
      });

      if (typeof data.touchCondition !== "string") {
        this.logger?.error(
          `[Arkveil] Touch condition for dataset ${datasetCode} violates the contract: ` +
            "the response is missing touchCondition. Denying rather than proceeding unchecked.",
        );
        return {
          touchCondition: DENY_CONDITION,
          mode: data.mode ?? MODE_UNAVAILABLE,
          reason: CONTRACT_VIOLATION,
        };
      }
      this.reportConfigurationGap("Touch condition", datasetCode, data.reason);
      this.flagDegradedMode(
        "touch condition",
        `dataset ${datasetCode}`,
        data.mode,
      );
      return data;
    } catch (error) {
      this.logger?.error(
        `[Arkveil] Touch condition request failed for dataset ${datasetCode}; failing closed (${DENY_CONDITION}):`,
        error,
      );
      return { touchCondition: DENY_CONDITION, mode: MODE_UNAVAILABLE };
    }
  }

  /**
   * POST to a data-conditions endpoint. Shares base URL, versioning, auth,
   * and retry behavior with `checkPermission`; throws on non-OK responses so
   * the callers can apply their fail-closed defaults.
   */
  private async postConditions<T>(
    endpoint: "read" | "write" | "touch",
    body: Record<string, unknown>,
  ): Promise<T> {
    const url = `${this.serviceUrl}/api/${this.version}/abac/conditions/${endpoint}`;

    const response = await fetchWithRetry(
      url,
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": `${this.apiKey}`,
        },
        body: JSON.stringify(body),
      },
      {
        timeout: this.timeout,
        retryAttempts: this.retryAttempts,
      },
    );

    if (!response.ok) {
      const message = await response.text().catch(() => "");
      throw new Error(
        `Conditions request failed: ${response.status} ${response.statusText}${
          message ? ` — ${message}` : ""
        }`,
      );
    }

    // Responses gain fields additively; anything unknown is passed through.
    return (await response.json()) as T;
  }

  /**
   * `METADATA_MISSING` names a configuration gap — the dataset is not
   * registered in Arkveil — and `CONTRACT_VIOLATION` a response the SDK could
   * not honor. Both deny, and both are logged distinctly from an ordinary
   * policy deny so operators see something to fix rather than a rule at work.
   * `ATTRIBUTE_INCOMPATIBLE` names a payload value of the wrong type for its
   * attribute schema: it does not deny by itself — the SQL is applied exactly
   * as returned — but it is a defect in the payload or the schema, so it is
   * logged as a warning rather than passed over in silence.
   */
  private reportConfigurationGap(
    operation: string,
    datasetCode: string,
    reason: string | undefined,
  ): void {
    if (reason === METADATA_MISSING) {
      this.logger?.error(
        `[Arkveil] ${operation} for dataset ${datasetCode} denied with reason ${METADATA_MISSING}: ` +
          "the dataset is not registered in Arkveil (configuration gap, not a policy deny).",
      );
    } else if (reason === ATTRIBUTE_INCOMPATIBLE) {
      this.logger?.warn(
        `[Arkveil] ${operation} for dataset ${datasetCode} reported ${ATTRIBUTE_INCOMPATIBLE}: ` +
          "an attribute value in the request does not match its declared schema type and was " +
          "evaluated as absent (fix the payload or the schema). The SQL is applied as returned.",
      );
    }
  }

  /** Non-"NORMAL" modes mean the serving side is degraded (e.g. a sidecar
   * past its staleness bound): the SQL is still honored, but the call is
   * flagged in diagnostics. */
  private flagDegradedMode(
    operation: string,
    subject: string,
    mode: string,
  ): void {
    if (mode !== "NORMAL") {
      this.logger?.warn(
        `[Arkveil] ${operation} for ${subject} served in degraded mode "${mode}".`,
      );
    }
  }

  /**
   * Handle denied access - runtime agnostic base implementation
   * Platform-specific SDKs should override this method
   *
   * @param req - Request object
   * @param res - Response object
   * @param next - Next function (optional)
   * @param onDenied - Custom denial handler (optional)
   * @param reason - The server's reason when the denial is not an ordinary
   *   policy deny (see {@link PermissionCheckResponse.reason}); handed to the
   *   custom handler as its third argument
   */
  protected handleDenied(
    req: any,
    res: any,
    next: any,
    onDenied?: (req: any, res: any, reason?: string) => void | Promise<void>,
    reason?: string,
  ) {
    const customHandler = onDenied || this.onDenied;

    if (customHandler) {
      return customHandler(req, res, reason);
    }

    // Platform-specific implementations (Node.js, etc.) should override this method
    throw new Error(
      "Access denied. No custom onDenied handler provided. " +
        "Either provide an onDenied handler in the constructor or use a platform-specific SDK.",
    );
  }
}
